### ISSUE TITLE
playerInspect.py doesn't work

### ISSUE THREAD

**Issue by stwalkerster** [GregoryAM-SP/The-Minecraft-Overviewer#26]
```
Traceback (most recent call last):
  File "playerInspect.py", line 17, in <module>
    from overviewer_core import items
ImportError: cannot import name 'items' from 'overviewer_core' (/home/stwalkerster/Projects/docker-minecraft-overviewer/git/overviewer_core/__init__.py)
```

I strongly suspect this is caused by 92e81042

**Comment by Gregory-AM** [comment]
I appreciate your PR's and will be checking into this issue ASAP.

**Comment by stwalkerster** [comment]
No problem - I've got quite a lot of changes queued up to create PRs for from our own fork 😁 

We've fixed this issue in particular was fixed by reverting 92e8104 (I'm still unsure why it was even removed in the first place), and applying an additional fix to the print statement. I'll throw a PR up for it later.
